# Interactive component
<!DOCTYPE html>
<meta charset="utf-8">

<script src="https://d3js.org/d3.v5.js"></script>

<h3 class='text-left'>
            The Airline Performance by Each Delay Reason In 2008
          </h3>
          <p>
            Nowadays, flight delays is a tricky problem for travelers. Each time when the travelers meet a delay situation, they are curious about the main reason that caused the flight delay. This interactive bar plot below shows the average delay time and the number of delays by each flight delay reason. Please feel free to click the two bottons below to see the results you want! 
            <br>
          </p>

<button onclick="update(data1)">Average Delay(mins)</button>
<button onclick="update(data2)"># of Delay(count*1000)</button>

<div id="my_dataviz"></div>


<script>

var data1 = [
   {group: "LateAircraft", value: 20.97670989},
   {group: "NAS", value: 16.1584616},
   {group: "Carrier", value: 15.7529572},
   {group: "Weather", value: 2.93824316},
   {group: "Security", value: 0.08045906}
];

var data2 = [
   {group: "LateAircraft", value: 27.2085},
   {group: "NAS", value: 27.5652},
   {group: "Carrier", value: 25.8289},
   {group: "Weather", value: 3.7599},
   {group: "Security", value: 0.2746}
];

var margin = {top: 30, right: 30, bottom: 70, left: 60},
    width = 460 - margin.left - margin.right,
    height = 400 - margin.top - margin.bottom;

var svg = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

var x = d3.scaleBand()
  .range([ 0, width ])
  .domain(data1.map(function(d) { return d.group; }))
  .padding(0.2);
svg.append("g")
  .attr("transform", "translate(0," + height + ")")
  .call(d3.axisBottom(x))

var y = d3.scaleLinear()
  .domain([0, 30])
  .range([ height, 0]);
svg.append("g")
  .attr("class", "myYaxis")
  .call(d3.axisLeft(y));

function update(data) {

  var u = svg.selectAll("rect")
    .data(data)

  u
    .enter()
    .append("rect")
    .merge(u)
    .transition()
    .duration(1000)
      .attr("x", function(d) { return x(d.group); })
      .attr("y", function(d) { return y(d.value); })
      .attr("width", x.bandwidth())
      .attr("height", function(d) { return height - y(d.value); })
      .attr("fill", "steelblue")
}

update(data1)

</script>
