--- 
title: "Airline On Time Performance"
author: "Ziyu Song, Zhengyi Fang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction


What is the most common reason for flight cancellation? What could I be delayed by? Which airline has the most delays? These are the problems that have been bothering travelers every time when they have a business trip, holiday travel, or studying abroad. Nowadays, flight delays and cancellations are tricky problems for travelers. In the U.S., there are lots of choices of airlines, airports, and carriers every day in most of the areas. In order to help people better understand the past performance of airlines and plan for their future trips, our group decided to apply advanced data visualization and analytics techniques to a large amount of real airline on-time data from Data Expo. In this project, we are going to provide the observations and insights from our data visuaization results to discuss the questions we are interested in and provide constructive suggestions.
